### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by gorgobacka** [metabrainz/musicbrainz-android#57]
I'm using the current version from Google Play Store (v4.2), but I don't get any results from the search.

I tried searches for releases and for artists. Always no results.

**Comment by amCap1712** [comment]
@gorgobacka Thanks for reporting this. However, I just tested it on my device and the search is working for me. Can you provide more details like the what the search terms were ? Also, can you make try cleaning the app data and switch to a different connection ?

**Comment by gorgobacka** [comment]
I tried cleaning the app data, cleaning the app cache, re-installing the app, using wifi and mobile internet.

Search term for artists is for example: Santana

I'm using Android 9.

What else can I provide to help you to solve this problem?

**Comment by amCap1712** [comment]
Something weird is happening and I am not sure what I tried the search on my device and get the results as in the attached screenshot.

![MusicBrainz Android search](https://user-images.githubusercontent.com/27751938/91904730-097a2880-ecc3-11ea-8e9b-2a914f537180.png)

That said, I agree that the search results is particularly unhelpful. If it fails, it shows nothing helpful to debug. We have debug logs in the application but we have no mechanism to collect those from the users. I'll put this on my todo list. In the meantime, I apologise for the inconvenience. I can only think of using the Android Debug Bridge. You can use it  to retrieve logs from your device and send to us for helping debug the issue. If you are not familiar with using it, I'll be happy to walk you through the process. You can ping me as **_lucifer** in **#metabrainz** irc channel on freenode and we can continue the debugging procedure there. If you are comfortable with some other mode of communication, I am fine with that as well.

**Comment by gorgobacka** [comment]
Ok, you got at least results. My list is always empty / no list is display. It doesn't matter what I search for.

I will read about the Android Debug Bridge and will try to use it. If I don't manage it, I will come to IRC.

Thanks in advance.

**Comment by gorgobacka** [comment]
I tested it today again and now the search is working.
