### ISSUE TITLE
GSOC-2021

### ISSUE THREAD

**Issue by SubhraPriyadarshinee** [metabrainz/musicbrainz-android#61]
Please report issues to the most appropriate project and component at
https://tickets.metabrainz.org

For informal discussions, simply join MetaBrainz community forums at
https://community.metabrainz.org

For an instant chat about development, join #metabrainz IRC channel at
irc://irc.freenode.net/metabrainz

Hey,
Is this project open for GSOC-2021?
I would like to contribute to this project and share my ideas.
Thankyou

**Comment by amCap1712** [comment]
Hi @SubhraPriyadarshinee, the organisations for GSoC-2021 have not yet been selected or announced. If MetaBrainz Foundation is selected, the project will be probably up for work. Feel free to join the #metabrainz IRC channel and discuss your ideas or get some pointers to get started on contributing.

**Comment by adarsh150999** [comment]
Hello Folks, 
I really want to look forward to contribute and participate in GSoC 21 . can anyone help me with guiding me what to start on with?

**Comment by amCap1712** [comment]
@adarsh150999 Please refer to the comment above.

**Comment by adarsh150999** [comment]
Hello sir,
Thank you so much for the help, since the organizations are not selected
yet , can I still be a part of it and start contributing to the on going
projects maybe ?
Thank you.

**Comment by amCap1712** [comment]
Yes, of course you can. All of the projects under the MetaBrainz Foundation are always to contributions.

**Comment by adarsh150999** [comment]
Awesome, thank you so much!
Please bare me with my mistakes if I make them , I've started recently.
