### ISSUE TITLE
F-droid support

### ISSUE THREAD

**Issue by theotheroracle** [metabrainz/musicbrainz-android#72]
currently only available on playstore, any plans to add to fdroid / izzydroid ?

**Comment by amCap1712** [comment]
Hi! We intend to publish the app on F-Droid as well. I had set up publishing the app to F-Droid myself sometime ago but it seems it was not done correctly. I'll take a look again at it soon.

**Comment by araccaine** [comment]
It is now available on F-Droid, thx :)

**Comment by theotheroracle** [comment]
:tada:

**Comment by amCap1712** [comment]
Closing as latest version is now available on F-Droid.
