### ISSUE TITLE
Sign In link leads to Page not Found 

### ISSUE THREAD

**Issue by araccaine** [metabrainz/musicbrainz-android#75]
Opening the sign in link in-app leads to Page not Found on musicbrainz.org website.

`https://musicbrainz.org/oauth2/authorizeauthorize?response_type=code&client_id=[my client ID]&redirect_uri=org.metabrainz.mobile://oauth&scope=profile%20collection%20tag%20rating`

Edit: there aren't spaces in this link but GitHub changes `% 20` to spaces as it seems.

**Comment by araccaine** [comment]
The word `authorize` is two times there. Deleting the first one leads to the right page.

**Comment by araccaine** [comment]
Clicking on `Allow Access` doesn't work. The App shows `failed to obtain access token`. 
I use the F droid version. Maybe the access token is only valid for play store version?

**Comment by SamHawkens** [comment]
I can confirm I have the same problem as @araccaine 
Also using the F-droid version.

**Comment by amCap1712** [comment]
HI all! Thanks for reporting the issue. Can you confirm you are on the latest version available on F-Droid (4.3)?

**Comment by araccaine** [comment]
I have indeed version 4.3 from F-Droid repo.

**Comment by SamHawkens** [comment]
yes, it says "4.3" when I click on "about"

**Comment by amCap1712** [comment]
Thanks for confirming. I have pushed a tag for version 4.6, the latest version available on Play Store. The F-Droid automated builder will hopefully pick it up soon and the latest version will be available on F-Droid. This should hopefully fix the issue.

**Comment by SamHawkens** [comment]
still no update on f-droid. Neither on google play. Both have version 4.3
any advise?

**Comment by araccaine** [comment]
It seems that in F-Droid the "newest" (last) version is 2.2.9 (version code 40) from 2021-06-24 15:30. You can see this in the app [F-Droid Build Status](https://f-droid.org/de/packages/de.storchp.fdroidbuildstatus/). The build was successfull but it it is the wrong version...? *visible confusion*

**Comment by amCap1712** [comment]
@araccaine Hi! Yes, the 2.2.9 (code 40) is the latest version. That was an error on my end. Apologies for the confusion. I am still new to F-Droid publishing so the next couple of releases may still be bumpy.

@SamHawkens As mentioned above you can see the F-Droid logs. My understanding of https://monitor.f-droid.org/builds/deploy is that F-Droid store was last updated on June 24 and the app was built shortly after that. Whenever, F-Droid store updates next, the new version should be available.

Regarding Google Play version, I see the latest update (June 1) there. Can you try checking from another device?

**Comment by araccaine** [comment]
@amCap1712
I have no idea how F-Droid works either, I just googled stuff and try to appear wise :D But IMHO there is no regular update schedule for f-droid repo. Sometimes there are updates daily, sometimes weekly. So we will sit and wait patiently.

@SamHawkens do you have the app from f-droid repo installed? Maybe then the PlayStore cannot show the latest version properly because they are "different" apps. I can see the last version from 2021-06-01 in PlayStore anyway.

**Comment by SamHawkens** [comment]
Actually I am not using the "real" play store but aurora store instead. It allows to install from play store without using a personal account. Anyway, it shows it wants to update from 37 to 40
 `4.3 (37) > 2.2.9 (40)`
I had to uninstall the f-droid version and installed from aurora afterwards.

Now login works :-) But when I click on collection it says "no result". Using a web browser I can see my collections. Did I miss anything?

**Comment by amCap1712** [comment]
Yes, the 2.2.9 is the latest version currently. Are your collections public? For private collections, you might need to enable Private Collections from settings. Also, note that the app does not support all types of collections currently (notably work and series are not supported, there may be others as well).

**Comment by SamHawkens** [comment]
Enabling Private Collections did the trick. Thanks a lot!

**Comment by amCap1712** [comment]
Hi all! The new version (2.2.9) is now available on F-Droid. Can you please update to it and see if that fixes the issue?

**Comment by ahstro** [comment]
Fixed it for me. Thanks! 😁💞
